CREATE TABLE IF NOT EXISTS `test` (
    `id` INT  AUTO_INCREMENT NOT NULL,
    `is_deleted` BOOLEAN default '0',
    `updated_datetime`  DATETIME  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    `created_datetime`  DATETIME  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;