apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-api.fullname" . }}
  labels:
{{ include "test-api.labels" . | indent 4 }}
data:
  notificationcenter.yaml: |
{{ toYaml .Values.config | indent 4 }}